name: build
on:
  workflow_dispatch:
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: build
      run: |
        pip3 install -r requirements.txt
        python3 user/html_readme.py
        cd provider
        curl -s -O https://samtupy.com/star_ci/balcon.exe
        curl -s -O https://samtupy.com/star_ci/sam.exe
        cd ..
        pyinstaller --noconfirm STAR.spec
    - uses: actions/upload-artifact@v4
      with:
        name: STAR_win64
        path: 'dist/STAR'

